# Generated by Django 3.2.5 on 2021-09-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('video', models.FileField(upload_to='admin/days/videos')),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WeekModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('video', models.FileField(upload_to='admin/weeks/videos')),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WhatYoullLearnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to="admin/what_you'll_learn/")),
                ('video', models.FileField(blank=True, null=True, upload_to="admin/what_you'll_learn/")),
                ('text', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('day', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.daymodel')),
                ('week', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.weekmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin/data/folder')),
                ('file_name', models.CharField(default='', max_length=255)),
                ('day', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.daymodel')),
                ('week', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.weekmodel')),
            ],
        ),
    ]
