# Generated by Django 3.2.5 on 2021-09-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_structures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldermodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='foldermodel',
            name='week',
        ),
        migrations.RemoveField(
            model_name='whatyoulllearnmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='whatyoulllearnmodel',
            name='week',
        ),
        migrations.DeleteModel(
            name='DayModel',
        ),
        migrations.DeleteModel(
            name='FolderModel',
        ),
        migrations.DeleteModel(
            name='WeekModel',
        ),
        migrations.DeleteModel(
            name='WhatYoullLearnModel',
        ),
    ]
