# Generated by Django 3.2.5 on 2021-09-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_structures', '0003_daymodel_foldermodel_weekmodel_whatyoulllearnmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('video', models.FileField(upload_to='admin/5days/videos')),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='foldermodel',
            name='five_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.fivedaymodel'),
        ),
        migrations.AddField(
            model_name='whatyoulllearnmodel',
            name='five_day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.fivedaymodel'),
        ),
    ]
