# Generated by Django 3.2.5 on 2021-09-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_structures', '0004_auto_20210928_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindWorkshopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('video', models.FileField(upload_to='admin/weeks/videos')),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='foldermodel',
            name='mind_workshop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.mindworkshopmodel'),
        ),
        migrations.AddField(
            model_name='whatyoulllearnmodel',
            name='mind_workshop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_structures.mindworkshopmodel'),
        ),
    ]
