# Generated by Django 3.2.5 on 2021-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_structures', '0005_auto_20210928_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymodel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='fivedaymodel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='mindworkshopmodel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='weekmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='daymodel',
            name='file',
            field=models.FileField(default='', upload_to='admin/days/video_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fivedaymodel',
            name='file',
            field=models.FileField(default='', upload_to='admin/5days/video_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mindworkshopmodel',
            name='file',
            field=models.FileField(default='', upload_to='admin/mind_workshop/video_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekmodel',
            name='file',
            field=models.FileField(default='', upload_to='admin/weeks/video_images'),
            preserve_default=False,
        ),
    ]
