# Generated by Django 3.2.5 on 2021-10-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('value', models.CharField(default='+ve', max_length=3)),
                ('impact', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('is_scaled', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('done_today', models.BooleanField(default=False)),
                ('thumbs_up_today', models.IntegerField(default=0)),
                ('thumbs_down_today', models.IntegerField(default=0)),
                ('thumbs_up_this_week', models.IntegerField(default=0)),
                ('thumbs_down_this_week', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LimitingBeliefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beliefs', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPositiveHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_or_before', models.CharField(default='', max_length=255)),
                ('act', models.CharField(default='', max_length=255)),
                ('celebrate', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('number_of_times', models.CharField(default=0, max_length=2)),
                ('behaviour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='behaviours.behaviourmapping')),
            ],
        ),
        migrations.CreateModel(
            name='DesignNegativeHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='', max_length=255)),
                ('make_less_obvious', models.CharField(default='', max_length=255)),
                ('make_harder', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('number_of_times', models.CharField(default=0, max_length=2)),
                ('behaviour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='behaviours.behaviourmapping')),
            ],
        ),
    ]
