# Generated by Django 3.2.5 on 2021-08-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_or_before', models.CharField(default='', max_length=255)),
                ('act', models.CharField(default='', max_length=255)),
                ('celebrate', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('behavior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.behaviourmaps')),
            ],
        ),
    ]
