# Generated by Django 3.2.5 on 2021-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_behaviourmaps_is_scaled'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourmaps',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
