# Generated by Django 3.2.5 on 2021-08-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_behaviourmaps_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitdesign',
            name='number_of_times',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
