# Generated by Django 3.2.5 on 2021-09-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_registereddatetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredDateTime',
        ),
    ]
