# Generated by Django 3.2.5 on 2021-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_registereddatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddatetime',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
