# Generated by Django 3.2.5 on 2021-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_registereddatetime_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourmaps',
            name='done_today',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RegisteredDateTime',
        ),
    ]
