# Generated by Django 3.2.5 on 2021-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_limitingbeliefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitingbeliefs',
            name='beliefs',
            field=models.CharField(max_length=10000),
        ),
    ]
