# Generated by Django 3.2.5 on 2021-09-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_limitingbeliefs_beliefs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitDesign',
            new_name='GoodHabitDesign',
        ),
        migrations.CreateModel(
            name='BadHabitDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='', max_length=255)),
                ('make_less_obvious', models.CharField(default='', max_length=255)),
                ('make_harder', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('number_of_times', models.CharField(default=0, max_length=2)),
                ('behavior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.behaviourmaps')),
            ],
        ),
    ]
