# Generated by Django 3.2.5 on 2021-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20210912_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourmaps',
            name='thumb_down_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviourmaps',
            name='thumb_up_clicked',
            field=models.IntegerField(default=0),
        ),
    ]
