# Generated by Django 3.2.5 on 2021-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20210915_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourmaps',
            name='thumb_down_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviourmaps',
            name='thumb_up_week',
            field=models.IntegerField(default=0),
        ),
    ]
