# Generated by Django 3.1.6 on 2021-07-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='vision_gallery_video_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
