# Generated by Django 3.2.5 on 2021-07-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_date',
            new_name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_amount_paid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='package_plan_id',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
