# Generated by Django 3.2.5 on 2021-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210727_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
