# Generated by Django 3.2.5 on 2021-10-15 23:09

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiveDayWaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipWaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.users')),
                ('user_token', models.CharField(default=accounts.models.generate_user_token, max_length=36)),
                ('aspiration_name', models.CharField(default='Aspiration', max_length=255)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('customer_id', models.CharField(default='', max_length=50)),
                ('scaled_habits', models.IntegerField(default=0)),
                ('yellow_habits', models.IntegerField(default=0)),
                ('red_habits', models.IntegerField(default=0)),
                ('green_habits', models.IntegerField(default=0)),
                ('negative_behaviors_done_this_week', models.CharField(default='0/0', max_length=10)),
                ('positive_behaviors_done_this_week', models.CharField(default='0/0', max_length=10)),
                ('all_positive_habits_this_week', models.CharField(default='[]', max_length=20)),
                ('all_scaled_habits_this_week', models.CharField(default='[]', max_length=20)),
                ('all_negative_habits_this_week', models.CharField(default='[]', max_length=20)),
                ('all_positive_habits_in_twelve_weeks', models.CharField(default='[]', max_length=40)),
                ('all_scaled_habits_in_twelve_weeks', models.CharField(default='[]', max_length=40)),
                ('all_negative_habits_in_twelve_weeks', models.CharField(default='[]', max_length=40)),
            ],
        ),
    ]
