# Generated by Django 3.1.6 on 2021-07-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0, max_length=5000)),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('last_amount_paid', models.IntegerField(max_length=100)),
                ('next_amount_to_be_paid', models.IntegerField(max_length=100)),
                ('last_pay_date', models.DateField()),
                ('next_pay_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
