# Generated by Django 3.1.6 on 2021-07-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_duration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_plan',
        ),
    ]
