# Generated by Django 3.2.5 on 2021-07-27 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210710_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='green_habits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='red_habits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='scaled_habits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='yellow_habits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
