# Generated by Django 3.2.5 on 2021-07-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210727_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,16}$')]),
        ),
    ]
