# Generated by Django 3.2.5 on 2021-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210913_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negative_habits_this_week',
            field=models.CharField(default='[]', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='positive_habits_this_week',
            field=models.CharField(default='[]', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='scaled_habits_this_week',
            field=models.CharField(default='[]', max_length=20),
        ),
    ]
