# Generated by Django 3.2.5 on 2021-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210916_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negative_habits_in_twelve_weeks',
            field=models.CharField(default='[]', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='positive_habits_in_twelve_weeks',
            field=models.CharField(default='[]', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='scaled_habits_in_twelve_weeks',
            field=models.CharField(default='[]', max_length=40),
        ),
    ]
